twitter_clone/accounts/urls.py
from django.urls import path
from .import views


app_name = 'accounts'

urlpatterns = [
    # path('login/', views.login_view, name='login'),
    # path('logout/', views.logout_view, name='logout'),

]

twitter_clone/tweets/urls.py
from django.urls import path
from . import views

app_name = 'tweets'

urlpatterns = [
    path('', views.tweet_list, name='tweet_list'),
    # path('media_tweets/', views.tweet_list, name='media_tweet_list'),

    path('<int:tweet_id>/', views.tweet_detail, name='tweet_detail'),
    path('create/', views.tweet_create, name='tweet_create'),
    
]

twitter_clone/twitter_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls', namespace='tweets')),
    path('', include('django.contrib.auth.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_clone/accounts/models.py
from django.db import models

# Create your models here.

twitter_clone/tweets/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

User = get_user_model()

# current_user = get_user_model()
def user_directory_path(instance, filename):
    return 'user_{}/{}'.format(instance.author.id, filename)

class Tweet(models.Model):
    author = models.ForeignKey(User, related_name='tweets', on_delete=models.CASCADE)
    body = models.CharField(max_length=280, blank=True)
    #DO NOT use null=True on Text and Charfield
    image = models.ImageField(upload_to=user_directory_path, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tweets_like', blank=True)
    users_retweet = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='tweets_retweet', blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{}'.format(str(self.id))

    def get_absolute_url(self):
        return reverse('tweets:tweet_detail', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.body and not self.image:
            raise ValidationError('tweet can not be empty :(')
        super().save(*args, **kwargs)
    
    

twitter_clone/accounts/forms.py
from django import forms


# class LoginForm(forms.Form):
#     username = forms.CharField()
#     password = forms.CharField(widget=forms.PasswordInput)

twitter_clone/tweets/forms.py
from django import forms
from .models import Tweet

class TweetCreationForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['body', 'image']

    

twitter_clone/accounts/views.py
from django.shortcuts import render,redirect
from tweets.models import Tweet
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

# def login_view(request):
#     if request.user.is_authenticated:
#         # message = 'ur already logined'
#         return redirect('tweets:tweet_list')

#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             new_user = authenticate(request, username=cd['username'], password=cd['password'])
#             if new_user is not None:
#                 if new_user.is_active:
#                     login(request, new_user)
#                     return redirect('tweets:tweet_list')
#                 else:
#                     return HttpResponse('ur not active')
#             else:
#                 return HttpResponse('username and password didn\'t match')
#     else:
#         form = LoginForm()
#     return render(request, 'accounts/login.html', {'form': form})


# def logout_view(request):
#     logout(request)
#     return redirect('accounts:login')

twitter_clone/tweets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Tweet
from .forms import TweetCreationForm
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.contrib import messages


@login_required
def tweet_list(request):
    tweets = Tweet.objects.filter(author=request.user)
    # if media:
    #     tweets = Tweet.objects.filter(image=True)     
    return render(request, 'tweets/tweet_list.html', {'tweets': tweets})

def tweet_detail(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    return render(request, 'tweets/tweet_detail.html', {'tweet': tweet})

def tweet_create(request):
    if request.method == 'POST':
        form = TweetCreationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_tweet = form.save(commit=False)
            new_tweet.author = request.user
            new_tweet.save()
            messages.success(request, 'ur tweet have been posted!')
            return redirect('tweets:tweet_list')
    else:
        form = TweetCreationForm(data=request.GET)
    return render(request, 'tweets/tweet_create.html', {'form': form})

# class TweetCreateView(CreateView):
#     model = Tweet
#     form_class = TweetCreationForm
#     template_name = 'tweets/tweet_create.html'
#     success_url = reverse_lazy('tweet_list')
    

twitter_clone/accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <nav>
        {% if user.is_authenticated %} 
            <ul>
                <li>
                    <a href=".">HOME</a>
                </li>
                <li>
                    <a href="{% url 'tweets:tweet_list' %}">PROFILE</a>
                </li>
            </ul>
            <h1>welcome, {{ user.username }}</h1>
            <a href="{% url 'logout' %}">LOG OUT</a>
            <a href="{% url 'password_change' %}">change your password?</a>
        {% else %}
            <a href="{% url 'login' %}">Login pls</a>
        {% endif %}
    </nav>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ messages.tags }}">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}    
        </ul> 
    {% endif %} 
{% block content %}
    
{% endblock content %}
    
</body>
</html>

twitter_clone/tweets/templates/tweets/_tweet.html
{% load static %}
{% load thumbnail %}
<h3>{{tweet.author}}</h3>
{% if tweet.created %}
    <p>just now</p>
{% else %}
    {{ tweet.created }}
{% endif %}

{% if tweet.body %}
    <h3>{{ tweet.body }}</h3>
{% endif %}
{% if tweet.image %}
    {% thumbnail tweet.image '300x300' crop='center' as im %}
        <a href="{{ tweet.image.url }}">
            <img src="{{ im.url }}" alt="">
        </a>
    {% endthumbnail %}
{% endif %}

twitter_clone/tweets/templates/tweets/tweet_create.html
<form method="POST" enctype="multipart/form-data">
    {% if form.errors %}
        {{ form.errors }}
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="TWEET ">
</form>

twitter_clone/tweets/templates/tweets/tweet_detail.html
<h1>tweet detail page</h1>

{% include 'tweets/_tweet.html' %}

twitter_clone/tweets/templates/tweets/tweet_list.html
{% extends 'base.html' %}
{% load thumbnail %}


{% block content %}

<h1>your tweets</h1>
<h3><a href="{% url 'tweets:tweet_create' %}">TWEET</a></h3>

<a href="{% url 'tweets:tweet_list' %}">TWEETS</a>
{% comment %} <a href="{% url 'tweets:media_tweet_list' media=True %}">Media</a> {% endcomment %}
{% for tweet in tweets %}
    {{ tweet.author }} 
    
    <a href="{{ tweet.get_absolute_url }}">{{ tweet.created|timesince }}</a>
    {% if tweet.body %}
        <h3>{{ tweet.body }}</h3>
    {% endif %}
    {% if tweet.image %}
        {% thumbnail tweet.image "300x300" crop="center" as im %}
        <a href="{{ tweet.image.url }}">
            <img src="{{ im.url }}" alt="">
        </a>
        {% endthumbnail %}
    {% endif %}
    <hr>
{% endfor %}
{% endblock content %}